<?php
/**
 * @file
 * Code for the Video feature.
 */

include_once 'cu_video.features.inc';

/**
 * Implements hook_theme_registry_alter().
 *
 * Let Drupal know that we've got node--slider.tpl.php in our module directory.
 */
function cu_video_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'cu_video');
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'node', $module_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('node');
  foreach ($hooks as $h) {
	  if (isset($theme_registry[$h]['theme paths'])) {
	    $first_element = array_shift($theme_registry[$h]['theme paths']);
	    array_unshift($theme_registry[$h]['theme paths'], array_shift($theme_registry[$h]['theme paths']), $module_path);
  	}
  }
}

/**
 * Implements hook_page_alter().
 */
function cu_video_page_alter(&$page) {
  // Add video css
  drupal_add_css(drupal_get_path('module', 'cu_video') . '/css/cu_video.css');
}